apiVersion: 1

datasources:
  - name: PGWatch-PostgreSQL
    type: postgres
    access: proxy
    uid: P031DD592934B2F1F
    url: sink-postgres:5432
    database: measurements
    user: pgwatch
    secureJsonData:
      password: pgwatchadmin
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    isDefault: false

  - name: PGWatch-Prometheus
    type: prometheus
    access: proxy
    uid: P7A0D6631BB10B34F
    url: http://sink-prometheus:9090
    isDefault: true
    basicAuth: true
    basicAuthUser: ${VM_AUTH_USERNAME}
    jsonData:
      scrapeInterval: '5s'
      queryTimeout: '5s'
      timeInterval: '5s'
      httpMethod: 'POST'
    secureJsonData:
      basicAuthPassword: ${VM_AUTH_PASSWORD}

  - name: Infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    uid: aerffb0z8rjlsc
    isDefault: false
    jsonData:
      auth_method: none
      allowed_hosts: []